# -*- coding: utf-8 -*-
"""notebook.json

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRw6Dd2nlOxEpSe4TePj7hsso_kpay_N

# Multiclass Student Performance Prediction with Explainable AI
**Name:** Fathima Aabidha Rifky

**Cardiff Met ID:** st20357374

**ICBT ID:** CL-MCSDS-CMU-10-04

**Dataset:** UCI Student Performance - https://archive.ics.uci.edu/dataset/320/student+performance

## 1. Problem framing

Educators often need early signals to identify students who may struggle before the end of the academic year. This project builds a machine learning framework to predict a student’s final performance category and explains the main factors behind predictions using visual explainability.

### Prediction target
The dataset includes three grades for the course:
- **G1**: first period grade (early in the year)
- **G2**: second period grade (mid-year)
- **G3**: final grade (end of year)

We convert **G3** into a multiclass outcome:
- **Low**: 0 to 9
- **Medium**: 10 to 14
- **High**: 15 to 20

### Two-stage experiment
1. **Early model** predicts the final category using background and behavioural factors only (no G1, no G2).
2. **Mid-term model** predicts the final category using background factors plus academic history (includes G1 and G2).

We expect accuracy to improve in the mid-term model because G1 and G2 carry direct academic signal. We also expect the explanation patterns to shift.

## 2. Setup

This notebook uses common Python libraries for data science and machine learning. If you are running in Google Colab, the installation cell below will ensure required packages are available.
"""

# If running in Google Colab, install extra packages.
# If you already have these installed, you can skip this cell.

!pip -q install xgboost shap

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    accuracy_score,
    f1_score,
    roc_auc_score,
    RocCurveDisplay
)

from sklearn.preprocessing import label_binarize
from sklearn.calibration import calibration_curve

from xgboost import XGBClassifier
import shap

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

print('Setup complete.')

"""## 3. Load the dataset (Portuguese only)

We use only `student-por.csv` to keep the study clean and reproducible.

Note: The UCI dataset also includes `student-mat.csv` and mentions that many students appear in both files. We do not merge the datasets here because there is no unique student identifier and merging can introduce leakage or mismatches.

### How to provide the file
Option A: Upload `student-por.csv` to Colab.
Option B: Place the CSV in the same folder as this notebook.

The dataset uses semicolon separators, so we will load it using `sep=';'`.
"""

# Update the filename if needed
CSV_PATH = 'student-por.csv'

df = pd.read_csv(CSV_PATH, sep=';')

print('Dataset loaded.')
print('Shape:', df.shape)
df.head()

"""## 4. Quick dataset overview

We will inspect:
- data types
- missing values
- basic summary statistics

This builds confidence that the dataset is usable and helps us plan preprocessing.
"""

df.info()

# Missing values overview
missing_counts = df.isna().sum().sort_values(ascending=False)
missing_counts[missing_counts > 0].head(20)

# Plot missing values per column (should be near zero for this dataset)
plt.figure(figsize=(10, 4))
plt.bar(missing_counts.index, missing_counts.values)
plt.title('Missing values by feature')
plt.xticks(rotation=90)
plt.ylabel('Count')
plt.tight_layout()
plt.show()

"""### Duplicate rows
We also check if there are exact duplicate rows in `por.csv`. This is different from the cross-file overlap note in the dataset description.
"""

duplicate_rows = df.duplicated().sum()
print('Exact duplicate rows in por.csv:', duplicate_rows)

"""## 5. Define the prediction target (multiclass)

We convert **G3** into three categories:
- Low: 0 to 9
- Medium: 10 to 14
- High: 15 to 20

This matches a practical educator view of performance bands.

We will keep the original G3 for visualization, then create a new label column.
"""

def grade_category(g3):
    if g3 <= 9:
        return 'Low'
    if g3 <= 14:
        return 'Medium'
    return 'High'

df['grade_cat'] = df['G3'].apply(grade_category)
# Numeric mapping only needed for XGBoost
LABEL_TO_NUM = {'Low': 0, 'Medium': 1, 'High': 2}
NUM_TO_LABEL = {v: k for k, v in LABEL_TO_NUM.items()}

df['grade_cat_num'] = df['grade_cat'].map(LABEL_TO_NUM)

df[['G3', 'grade_cat']].head()

df[['grade_cat', 'grade_cat_num']].drop_duplicates().sort_values('grade_cat_num')

# Distribution of raw final grades
plt.figure(figsize=(7, 4))
plt.hist(df['G3'], bins=21)
plt.title('Distribution of final grade (G3)')
plt.xlabel('G3')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

# Distribution of grade categories
cat_counts = df['grade_cat'].value_counts().reindex(['Low', 'Medium', 'High'])

plt.figure(figsize=(6, 4))
plt.bar(cat_counts.index, cat_counts.values)
plt.title('Grade category distribution')
plt.xlabel('Category')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

cat_counts

"""## 6. Exploratory Data Analysis (EDA)

This section looks for patterns that relate to performance.

We focus on features that are meaningful to educators and easy to interpret:
- absences
- studytime
- failures
- parental education
- support features (schoolsup, famsup)
- internet access

We will use simple, readable charts and write a short interpretation after each.
"""

# Helper to plot a numeric feature by category using boxplots
def boxplot_by_category(feature, title):
    data = [
        df.loc[df['grade_cat'] == 'Low', feature].values,
        df.loc[df['grade_cat'] == 'Medium', feature].values,
        df.loc[df['grade_cat'] == 'High', feature].values,
    ]
    plt.figure(figsize=(7, 4))
    plt.boxplot(data, tick_labels=['Low','Medium','High'])
    plt.title(title)
    plt.xlabel('Grade category')
    plt.ylabel(feature)
    plt.tight_layout()
    plt.show()

boxplot_by_category('absences', 'Absences by grade category')
boxplot_by_category('studytime', 'Study time by grade category')
boxplot_by_category('failures', 'Past failures by grade category')

# Parental education by category
def bar_mean_by_category(feature, title):
    means = df.groupby('grade_cat')[feature].mean().reindex(['Low', 'Medium', 'High'])
    plt.figure(figsize=(6, 4))
    plt.bar(means.index, means.values)
    plt.title(title)
    plt.xlabel('Grade category')
    plt.ylabel(f'Mean {feature}')
    plt.tight_layout()
    plt.show()
    return means

medu_means = bar_mean_by_category('Medu', 'Mean mother education (Medu) by grade category')
fedu_means = bar_mean_by_category('Fedu', 'Mean father education (Fedu) by grade category')
medu_means, fedu_means

# Categorical feature association with grade category using stacked bar chart
def stacked_bar(feature, title):
    ct = pd.crosstab(df[feature], df['grade_cat'], normalize='index').reindex(columns=['Low', 'Medium', 'High'])
    ct.plot(kind='bar', stacked=True, figsize=(8, 4))
    plt.title(title)
    plt.xlabel(feature)
    plt.ylabel('Proportion within group')
    plt.legend(title='Grade category', bbox_to_anchor=(1.02, 1), loc='upper left')
    plt.tight_layout()
    plt.show()
    return ct

schoolsup_ct = stacked_bar('schoolsup', 'Extra educational support (schoolsup) vs grade category')
famsup_ct = stacked_bar('famsup', 'Family educational support (famsup) vs grade category')
internet_ct = stacked_bar('internet', 'Internet access at home vs grade category')

schoolsup_ct.head(), famsup_ct.head(), internet_ct.head()

"""### Correlation heatmap (numeric features)

Correlation helps us see which numeric variables tend to move together. For example, we expect G1, G2, and G3 to have strong relationships.

We will compute correlations only for numeric columns.
"""

numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
corr = df[numeric_cols].corr()

plt.figure(figsize=(10, 8))
plt.imshow(corr.values, aspect='auto')
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.index)), corr.index)
plt.title('Correlation heatmap (numeric features)')
plt.tight_layout()
plt.show()

corr[['G1', 'G2', 'G3']].sort_values(by='G3', ascending=False).head(10)

"""## 7. Preprocessing plan

We will:
- keep all features
- encode categorical variables using one-hot encoding
- standardize numeric variables only for Logistic Regression
- use a stratified 80/20 train-test split

We build pipelines so that preprocessing is applied consistently and reproducibly.

## 8. Define feature sets for the two-stage experiment

### Stage 1: Early model
Exclude **G1** and **G2** (no academic history).

### Stage 2: Mid-term model
Include **G1** and **G2**.

In both stages, the target is the grade category derived from **G3**.
"""

TARGET_COL = 'grade_cat'

# Remove target and any target-derived columns to prevent leakage
DROP_COLS = ['G3', 'grade_cat', 'grade_cat_num']
all_features = [c for c in df.columns if c not in DROP_COLS]

# Early model excludes G1 and G2
early_features = [c for c in all_features if c not in ['G1', 'G2']]

# Mid-term includes G1 and G2
mid_features = all_features.copy()

print('Total features:', len(all_features))
print('Early features:', len(early_features))
print('Mid-term features:', len(mid_features))

early_features[:10], mid_features[:10]

"""## 9. Train-test split (stratified 80/20)

We split the dataset once into training and testing sets.
Stratification keeps the Low, Medium, High proportions similar in both sets.

We will reuse the same split for all models within a stage to ensure fair comparison.
"""

def make_split(features):
    X = df[features].copy()
    y = df[TARGET_COL].copy()
    return train_test_split(
        X, y,
        test_size=0.2,
        random_state=RANDOM_STATE,
        stratify=y
    )

X_train_e, X_test_e, y_train_e, y_test_e = make_split(early_features)
X_train_m, X_test_m, y_train_m, y_test_m = make_split(mid_features)

# Numeric y for XGBoost only (same split, just mapped labels)
y_train_e_xgb = y_train_e.map(LABEL_TO_NUM)
y_test_e_xgb  = y_test_e.map(LABEL_TO_NUM)

y_train_m_xgb = y_train_m.map(LABEL_TO_NUM)
y_test_m_xgb  = y_test_m.map(LABEL_TO_NUM)

print('Early split:', X_train_e.shape, X_test_e.shape)
print('Mid split:', X_train_m.shape, X_test_m.shape)

print('Early train distribution:')
print(y_train_e.value_counts(normalize=True).reindex(['Low','Medium','High']))
print('Early test distribution:')
print(y_test_e.value_counts(normalize=True).reindex(['Low','Medium','High']))

"""## 10. Build preprocessing pipelines

We detect categorical and numeric columns for each stage.

- Categorical columns use one-hot encoding
- Numeric columns use scaling only for Logistic Regression

We will create:
- one pipeline for Logistic Regression
- one pipeline for Random Forest
- one pipeline for XGBoost
"""

def get_column_types(X):
    cat_cols = X.select_dtypes(include=['object']).columns.tolist()
    num_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    return cat_cols, num_cols

def make_preprocessor(cat_cols, num_cols, scale_numeric=False):
    transformers = []
    transformers.append(('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols))
    if scale_numeric:
        transformers.append(('num', StandardScaler(), num_cols))
    else:
        transformers.append(('num', 'passthrough', num_cols))
    return ColumnTransformer(transformers)

cat_e, num_e = get_column_types(X_train_e)
cat_m, num_m = get_column_types(X_train_m)

print('Early categorical:', len(cat_e), 'Early numeric:', len(num_e))
print('Mid categorical:', len(cat_m), 'Mid numeric:', len(num_m))

"""## 11. Model training and evaluation helper functions

We will evaluate all models using:
- Accuracy
- Macro F1
- Weighted F1
- Confusion matrix
- Multiclass ROC-AUC (one-vs-rest)

We keep the code modular to avoid repetition and make results consistent.
"""

CLASS_ORDER = ['Low', 'Medium', 'High']

def reorder_proba_to_class_order(model, y_proba, class_order):
    """
    Ensures probability columns match the requested class_order.
    sklearn returns proba columns in model.classes_ order, which may differ.
    """
    # If this is a pipeline, classes_ is on the final estimator
    clf = model.named_steps['model'] if hasattr(model, "named_steps") else model
    model_classes = list(clf.classes_)
    idx = [model_classes.index(c) for c in class_order]
    return y_proba[:, idx]

def multiclass_roc_auc(y_true, y_proba_aligned, class_order=CLASS_ORDER):
    y_true_bin = label_binarize(y_true, classes=class_order)
    return roc_auc_score(y_true_bin, y_proba_aligned, average='macro', multi_class='ovr')

def plot_confusion(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred, labels=CLASS_ORDER)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=CLASS_ORDER)
    disp.plot(values_format='d')
    plt.title(title)
    plt.tight_layout()
    plt.show()

def plot_multiclass_roc(y_true, y_proba_aligned, title, class_order=CLASS_ORDER):
    y_true_bin = label_binarize(y_true, classes=class_order)
    plt.figure(figsize=(7, 5))
    for i, cls in enumerate(class_order):
        RocCurveDisplay.from_predictions(
            y_true_bin[:, i],
            y_proba_aligned[:, i],
            name=f'{cls} vs rest'
        )
    plt.title(title)
    plt.tight_layout()
    plt.show()

def evaluate_model_text(name, model, X_train, X_test, y_train, y_test):
    """
    For Logistic Regression and Random Forest with text labels (Low, Medium, High).
    """
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)

    # Align proba columns to CLASS_ORDER
    y_proba_aligned = reorder_proba_to_class_order(model, y_proba, CLASS_ORDER)

    acc = accuracy_score(y_test, y_pred)
    f1_macro = f1_score(y_test, y_pred, average='macro')
    f1_weighted = f1_score(y_test, y_pred, average='weighted')
    auc = multiclass_roc_auc(y_test, y_proba_aligned, CLASS_ORDER)

    results = {
        'model': name,
        'accuracy': acc,
        'f1_macro': f1_macro,
        'f1_weighted': f1_weighted,
        'roc_auc_ovr_macro': auc
    }

    print('Model:', name)
    print('Accuracy:', round(acc, 4))
    print('Macro F1:', round(f1_macro, 4))
    print('Weighted F1:', round(f1_weighted, 4))
    print('ROC-AUC (OvR macro):', round(auc, 4))
    print('\nClassification report:\n')
    print(classification_report(y_test, y_pred, labels=CLASS_ORDER))

    plot_confusion(y_test, y_pred, f'Confusion matrix: {name}')
    plot_multiclass_roc(y_test, y_proba_aligned, f'ROC curves (OvR): {name}')

    return results, model

def evaluate_model_xgb(name, model, X_train, X_test, y_train_num, y_test_num):
    """
    For XGBoost with numeric labels (0,1,2) but reports in Low/Medium/High.
    """
    model.fit(X_train, y_train_num)
    y_pred_num = model.predict(X_test)
    y_proba = model.predict_proba(X_test)

    # For XGBoost, classes_ should be [0,1,2]. Align them to numeric order [0,1,2]
    y_proba_aligned_num = reorder_proba_to_class_order(model, y_proba, [0, 1, 2])

    # Convert numeric to text for reporting
    y_test = y_test_num.map(NUM_TO_LABEL)
    y_pred = pd.Series(y_pred_num, index=y_test.index).map(NUM_TO_LABEL)

    acc = accuracy_score(y_test, y_pred)
    f1_macro = f1_score(y_test, y_pred, average='macro')
    f1_weighted = f1_score(y_test, y_pred, average='weighted')

    # Convert aligned numeric proba to aligned text proba by mapping order 0,1,2 -> Low,Medium,High
    y_proba_aligned_text = y_proba_aligned_num  # columns are already [0,1,2] meaning Low,Medium,High by our mapping
    auc = multiclass_roc_auc(y_test_num, y_proba_aligned_num, [0, 1, 2])
    results = {
        'model': name,
        'accuracy': acc,
        'f1_macro': f1_macro,
        'f1_weighted': f1_weighted,
        'roc_auc_ovr_macro': auc
    }

    print('Model:', name)
    print('Accuracy:', round(acc, 4))
    print('Macro F1:', round(f1_macro, 4))
    print('Weighted F1:', round(f1_weighted, 4))
    print('ROC-AUC (OvR macro):', round(auc, 4))
    print('\nClassification report:\n')
    print(classification_report(y_test, y_pred, labels=CLASS_ORDER))

    plot_confusion(y_test, y_pred, f'Confusion matrix: {name}')
    plot_multiclass_roc(y_test, y_proba_aligned_text, f'ROC curves (OvR): {name}')

    return results, model

"""## 12. Experiment A: Early model (exclude G1 and G2)

In this stage, we predict the final performance category using background and behavioural features only.

This is the early warning scenario.
"""

# Build models for Early stage
pre_lr_e = make_preprocessor(cat_e, num_e, scale_numeric=True)
pre_tree_e = make_preprocessor(cat_e, num_e, scale_numeric=False)

lr = LogisticRegression(max_iter=2000, random_state=RANDOM_STATE)
rf = RandomForestClassifier(random_state=RANDOM_STATE)

xgb = XGBClassifier(
    random_state=RANDOM_STATE,
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss'
)

lr_pipe_e = Pipeline(steps=[('prep', pre_lr_e), ('model', lr)])
rf_pipe_e = Pipeline(steps=[('prep', pre_tree_e), ('model', rf)])
xgb_pipe_e = Pipeline(steps=[('prep', pre_tree_e), ('model', xgb)])

early_results = []
trained_early = {}

# Logistic Regression and Random Forest use text labels
res, fitted = evaluate_model_text('Logistic Regression (Early)', lr_pipe_e, X_train_e, X_test_e, y_train_e, y_test_e)
early_results.append(res)
trained_early['Logistic Regression (Early)'] = fitted

res, fitted = evaluate_model_text('Random Forest (Early)', rf_pipe_e, X_train_e, X_test_e, y_train_e, y_test_e)
early_results.append(res)
trained_early['Random Forest (Early)'] = fitted

# XGBoost uses numeric labels
res, fitted = evaluate_model_xgb('XGBoost (Early)', xgb_pipe_e, X_train_e, X_test_e, y_train_e_xgb, y_test_e_xgb)
early_results.append(res)
trained_early['XGBoost (Early)'] = fitted

early_results_df = pd.DataFrame(early_results).sort_values(by='f1_macro', ascending=False)
early_results_df

"""### Early stage comparison summary

We compare models using Macro F1 as a primary metric because it treats all classes fairly.
Accuracy alone can hide poor performance on minority categories.
"""

plt.figure(figsize=(8, 4))
plt.bar(early_results_df['model'], early_results_df['f1_macro'])
plt.title('Early stage: Macro F1 by model')
plt.xticks(rotation=45, ha='right')
plt.ylabel('Macro F1')
plt.tight_layout()
plt.show()

early_results_df

"""## 13. Experiment B: Mid-term model (include G1 and G2)

In this stage, we include academic history (G1 and G2). This should improve prediction quality.

We train and evaluate the same three models, using the same train-test split strategy.
"""

# Build models for Mid-term stage
pre_lr_m = make_preprocessor(cat_m, num_m, scale_numeric=True)
pre_tree_m = make_preprocessor(cat_m, num_m, scale_numeric=False)

lr_m = LogisticRegression(max_iter=2000, random_state=RANDOM_STATE)
rf_m = RandomForestClassifier(random_state=RANDOM_STATE)

xgb_m = XGBClassifier(
    random_state=RANDOM_STATE,
    objective='multi:softprob',
    num_class=3,
    eval_metric='mlogloss'
)

lr_pipe_m = Pipeline(steps=[('prep', pre_lr_m), ('model', lr_m)])
rf_pipe_m = Pipeline(steps=[('prep', pre_tree_m), ('model', rf_m)])
xgb_pipe_m = Pipeline(steps=[('prep', pre_tree_m), ('model', xgb_m)])

mid_results = []
trained_mid = {}

# Logistic Regression and Random Forest use text labels
res, fitted = evaluate_model_text('Logistic Regression (Mid)', lr_pipe_m, X_train_m, X_test_m, y_train_m, y_test_m)
mid_results.append(res)
trained_mid['Logistic Regression (Mid)'] = fitted

res, fitted = evaluate_model_text('Random Forest (Mid)', rf_pipe_m, X_train_m, X_test_m, y_train_m, y_test_m)
mid_results.append(res)
trained_mid['Random Forest (Mid)'] = fitted

# XGBoost uses numeric labels
res, fitted = evaluate_model_xgb('XGBoost (Mid)', xgb_pipe_m, X_train_m, X_test_m, y_train_m_xgb, y_test_m_xgb)
mid_results.append(res)
trained_mid['XGBoost (Mid)'] = fitted

mid_results_df = pd.DataFrame(mid_results).sort_values(by='f1_macro', ascending=False)
mid_results_df

"""### Mid-term stage comparison summary

We visualize Macro F1 to see which model performs best when G1 and G2 are included.
"""

plt.figure(figsize=(8, 4))
plt.bar(mid_results_df['model'], mid_results_df['f1_macro'])
plt.title('Mid-term stage: Macro F1 by model')
plt.xticks(rotation=45, ha='right')
plt.ylabel('Macro F1')
plt.tight_layout()
plt.show()

mid_results_df

"""## 14. Early vs Mid-term comparison

This section directly answers the main experimental question:
Does performance improve when academic history (G1 and G2) is included?

We merge results into one comparison table and add a simple chart.
"""

early_results_df2 = early_results_df.copy()
early_results_df2['stage'] = 'Early'

mid_results_df2 = mid_results_df.copy()
mid_results_df2['stage'] = 'Mid-term'

comparison_df = pd.concat([early_results_df2, mid_results_df2], ignore_index=True)
comparison_df = comparison_df[['stage', 'model', 'accuracy', 'f1_macro', 'f1_weighted', 'roc_auc_ovr_macro']]
comparison_df

# Plot Early vs Mid-term for each model family
def family_name(model_name):
    if 'Logistic' in model_name:
        return 'Logistic Regression'
    if 'Random Forest' in model_name:
        return 'Random Forest'
    return 'XGBoost'

comparison_df['family'] = comparison_df['model'].apply(family_name)

pivot = comparison_df.pivot_table(index='family', columns='stage', values='f1_macro')
pivot = pivot.reindex(['Logistic Regression', 'Random Forest', 'XGBoost'])

plt.figure(figsize=(7, 4))
x = np.arange(len(pivot.index))
width = 0.35
plt.bar(x - width/2, pivot['Early'], width, label='Early')
plt.bar(x + width/2, pivot['Mid-term'], width, label='Mid-term')
plt.xticks(x, pivot.index, rotation=0)
plt.ylabel('Macro F1')
plt.title('Early vs Mid-term performance (Macro F1)')
plt.legend()
plt.tight_layout()
plt.show()

pivot

"""## 15. Select the best-performing model

We pick the best model using Macro F1 from the mid-term stage. This is the model we will explain using SHAP.

We keep XAI focused on the best model to keep the analysis clear and professional.
"""

best_row = mid_results_df.sort_values(by='f1_macro', ascending=False).iloc[0]
best_model_name = best_row['model']
print('Best model selected:', best_model_name)
best_model = trained_mid[best_model_name]

best_row

"""## 16. Explainable AI with SHAP (best model only)

### What SHAP gives us
SHAP provides:
- Global explanations: which features matter most overall across all students.
- Local explanations: why the model predicted a specific category for a specific student.

For tree-based models such as Random Forest and XGBoost, SHAP is especially effective because the TreeExplainer method can accurately explain ensemble tree models. This makes it well suited for understanding how the best-performing model reaches its decisions.

If the best model is not tree-based, we can still apply SHAP, but the underlying explainer method may differ slightly depending on the model type.
"""

# Prepare transformed feature matrix for SHAP
# We need access to the preprocessor and the final model.

prep = best_model.named_steps['prep']
clf = best_model.named_steps['model']

X_train_trans = prep.fit_transform(X_train_m)
X_test_trans = prep.transform(X_test_m)

# Build feature names after one-hot encoding
ohe = prep.named_transformers_['cat']
cat_features = cat_m
num_features = num_m

ohe_feature_names = ohe.get_feature_names_out(cat_features).tolist()
all_feature_names = ohe_feature_names + num_features

# Convert to dense for SHAP plotting if needed
X_test_trans_dense = X_test_trans
try:
    if hasattr(X_test_trans, 'toarray'):
        X_test_trans_dense = X_test_trans.toarray()
except Exception:
    pass

print('Transformed test shape:', np.array(X_test_trans_dense).shape)
print('Feature names count:', len(all_feature_names))

shap.initjs()

# Prefer TreeExplainer for tree-based models (XGB + RandomForest)
if isinstance(clf, (XGBClassifier, RandomForestClassifier)):
    explainer = shap.TreeExplainer(clf)
    shap_values = explainer(X_test_trans_dense)   # returns Explanation
else:
    explainer = shap.Explainer(clf, X_train_trans)
    shap_values = explainer(X_test_trans_dense)

print('SHAP values computed.')

"""### 16.1 Global explanation: SHAP summary plot

This plot shows which features contribute the most to predictions across the test set.
For multiclass models, SHAP returns values per class. We will display the summary for each class if available.
"""

if isinstance(clf, XGBClassifier):
    # shap_values is a list: one array per class
    for i, cls in enumerate(CLASS_ORDER):
        plt.figure(figsize=(8, 5))
        shap.summary_plot(shap_values[i], X_test_trans_dense, feature_names=all_feature_names, show=False)
        plt.title(f'SHAP summary plot for class: {cls}')
        plt.tight_layout()
        plt.show()
else:
    plt.figure(figsize=(8, 5))
    shap.summary_plot(shap_values, X_test_trans_dense, feature_names=all_feature_names, show=False)
    plt.title('SHAP summary plot (global)')
    plt.tight_layout()
    plt.show()

"""### 16.2 Local explanations: 3 example students

We explain three individual predictions:
- one predicted Low
- one predicted Medium
- one predicted High

This helps translate model reasoning into educator-friendly insights.
"""

# Get predicted class for each student in the test set
y_test_pred = best_model.predict(X_test_m)
test_df = X_test_m.copy()
test_df['true'] = y_test_m.values
test_df['pred'] = y_test_pred

examples = {}
for cls in CLASS_ORDER:
    idxs = test_df.index[test_df['pred'] == cls].tolist()
    if len(idxs) > 0:
        examples[cls] = idxs[0]

print('Example indices by predicted class:', examples)

example_indices = [examples[c] for c in CLASS_ORDER if c in examples]
example_indices

# Explain each example using SHAP
for cls in CLASS_ORDER:
    if cls not in examples:
        continue
    idx = examples[cls]
    row_position = list(X_test_m.index).index(idx)

    print('---')
    print('Predicted class:', cls)
    print('True class:', test_df.loc[idx, 'true'])

    x_row = X_test_trans_dense[row_position:row_position+1]

    if isinstance(clf, XGBClassifier):
        class_i = CLASS_ORDER.index(cls)
        plt.figure(figsize=(8, 5))
        shap.waterfall_plot(
            shap.Explanation(
                values=shap_values[class_i][row_position],
                base_values=explainer.expected_value[class_i],
                data=x_row[0],
                feature_names=all_feature_names
            ),
            show=False
        )
        plt.title(f'Local SHAP explanation (waterfall) for predicted class: {cls}')
        plt.tight_layout()
        plt.show()
    else:
        class_i = CLASS_ORDER.index(cls)
        shap.plots.bar(shap_values[row_position, :, class_i], show=False)
        plt.title(f'Local SHAP explanation (bar) for predicted class: {cls}')
        plt.tight_layout()
        plt.show()

"""## 17. Calibration and trust check (best model)

Calibration checks whether predicted probabilities match real outcomes.
For multiclass problems, calibration is usually evaluated one class at a time using one-vs-rest.

We will plot calibration curves for each class.
If the curve stays close to the diagonal, predicted probabilities are reliable.

This supports trustworthy analytics because it helps educators understand whether the model is overconfident.
"""

# Predicted probabilities for the best model on the mid-term test set (aligned to CLASS_ORDER)
proba_raw = best_model.predict_proba(X_test_m)
proba = reorder_proba_to_class_order(best_model, proba_raw, CLASS_ORDER)
y_true = y_test_m.values

# Plot calibration per class using one-vs-rest
plt.figure(figsize=(7, 6))
for i, cls in enumerate(CLASS_ORDER):
    y_bin = (y_true == cls).astype(int)
    prob_cls = proba[:, i]
    frac_pos, mean_pred = calibration_curve(y_bin, prob_cls, n_bins=10, strategy='uniform')
    plt.plot(mean_pred, frac_pos, marker='o', label=f'{cls} vs rest')

plt.plot([0, 1], [0, 1], linestyle='--')
plt.title('Calibration curves (one-vs-rest) for best model')
plt.xlabel('Mean predicted probability')
plt.ylabel('Fraction of positives')
plt.legend()
plt.tight_layout()
plt.show()

clf = best_model.named_steps["model"]
print("Model classes_ order:", list(clf.classes_))
print("Your CLASS_ORDER:", CLASS_ORDER)

print("proba columns aligned to:", CLASS_ORDER)
print("first row probs (Low, Medium, High):", proba[0])
print("sum:", proba[0].sum())

"""## 18. Final summary tables

We present clean summary tables for reporting:
- Early stage results
- Mid-term stage results
- Combined comparison

These tables can be copied into the report with minimal editing.
"""

print('Early stage results:')
display(early_results_df)

print('Mid-term stage results:')
display(mid_results_df)

print('Combined comparison:')
display(comparison_df.sort_values(by=['stage', 'f1_macro'], ascending=[True, False]))

# --- Save the selected best model (full sklearn Pipeline) to a pickle and download it ---

import pickle

model_filename = f"best_model_{best_model_name}.pkl"

# Save (pickle) the entire pipeline: preprocessing + model
with open(model_filename, "wb") as f:
    pickle.dump(best_model, f)

print("Saved model to:", model_filename)

# Download (Google Colab)
from google.colab import files
files.download(model_filename)

# Load model (if you already loaded it, skip this)
import pickle
with open("/content/best_model_Random Forest (Mid).pkl", "rb") as f:
    model = pickle.load(f)

# Predict on Mid-term test set
pred = model.predict(X_test_m)

from sklearn.metrics import accuracy_score, f1_score, classification_report
print("Accuracy:", accuracy_score(y_test_m, pred))
print("Macro F1:", f1_score(y_test_m, pred, average="macro"))
print(classification_report(y_test_m, pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

pred = model.predict(X_test_m)

cm = confusion_matrix(y_test_m, pred, labels=['Low','Medium','High'])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Low','Medium','High'])
disp.plot(values_format='d')
plt.title("Best Model Confusion Matrix: Random Forest (Mid)")
plt.show()

import pandas as pd

test_inputs = pd.DataFrame([

# 1️⃣ Likely HIGH performer
{
'school':'GP','sex':'F','age':17,'address':'U','famsize':'GT3','Pstatus':'T',
'Medu':4,'Fedu':4,'Mjob':'teacher','Fjob':'teacher','reason':'course','guardian':'mother',
'traveltime':1,'studytime':4,'failures':0,'schoolsup':'no','famsup':'yes',
'paid':'no','activities':'yes','nursery':'yes','higher':'yes','internet':'yes',
'romantic':'no','famrel':5,'freetime':3,'goout':2,'Dalc':1,'Walc':1,
'health':5,'absences':2,'G1':15,'G2':16
},

# 2️⃣ Likely MEDIUM performer
{
'school':'GP','sex':'M','age':16,'address':'U','famsize':'LE3','Pstatus':'T',
'Medu':2,'Fedu':2,'Mjob':'services','Fjob':'other','reason':'home','guardian':'father',
'traveltime':2,'studytime':2,'failures':0,'schoolsup':'no','famsup':'yes',
'paid':'no','activities':'yes','nursery':'yes','higher':'yes','internet':'yes',
'romantic':'yes','famrel':4,'freetime':4,'goout':3,'Dalc':1,'Walc':2,
'health':4,'absences':5,'G1':12,'G2':12
},

# 3️⃣ Likely LOW performer
{
'school':'MS','sex':'M','age':18,'address':'R','famsize':'GT3','Pstatus':'A',
'Medu':1,'Fedu':1,'Mjob':'other','Fjob':'other','reason':'reputation','guardian':'mother',
'traveltime':3,'studytime':1,'failures':2,'schoolsup':'yes','famsup':'no',
'paid':'yes','activities':'no','nursery':'no','higher':'no','internet':'no',
'romantic':'yes','famrel':3,'freetime':5,'goout':5,'Dalc':3,'Walc':4,
'health':3,'absences':15,'G1':7,'G2':8
},

# 4️⃣ Borderline MEDIUM/HIGH
{
'school':'GP','sex':'F','age':15,'address':'U','famsize':'GT3','Pstatus':'T',
'Medu':3,'Fedu':3,'Mjob':'health','Fjob':'services','reason':'course','guardian':'mother',
'traveltime':1,'studytime':3,'failures':0,'schoolsup':'no','famsup':'yes',
'paid':'no','activities':'yes','nursery':'yes','higher':'yes','internet':'yes',
'romantic':'no','famrel':4,'freetime':3,'goout':2,'Dalc':1,'Walc':1,
'health':4,'absences':3,'G1':14,'G2':14
},

# 5️⃣ Risk student (likely LOW/MEDIUM)
{
'school':'MS','sex':'F','age':17,'address':'R','famsize':'LE3','Pstatus':'T',
'Medu':2,'Fedu':1,'Mjob':'services','Fjob':'services','reason':'other','guardian':'father',
'traveltime':4,'studytime':1,'failures':1,'schoolsup':'yes','famsup':'no',
'paid':'yes','activities':'no','nursery':'yes','higher':'yes','internet':'no',
'romantic':'yes','famrel':2,'freetime':5,'goout':4,'Dalc':2,'Walc':3,
'health':3,'absences':12,'G1':9,'G2':10
}

])

predictions = model.predict(test_inputs)
print(predictions)

proba_raw = model.predict_proba(test_inputs)
proba = reorder_proba_to_class_order(model, proba_raw, CLASS_ORDER)

for i, p in enumerate(predictions):
    print(f"\nStudent {i+1}")
    print("Prediction:", p)
    print("Probabilities (Low, Medium, High):", proba[i])

import os

os.makedirs("results", exist_ok=True)
print("results folder created.")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Predict again (if needed)
pred = model.predict(X_test_m)

cm = confusion_matrix(y_test_m, pred, labels=['Low','Medium','High'])
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                              display_labels=['Low','Medium','High'])

plt.figure(figsize=(6,5))
disp.plot(values_format='d')
plt.title("Confusion Matrix - Random Forest (Mid)")
plt.tight_layout()

plt.savefig("results/confusion_matrix.png", dpi=300)
plt.close()

print("Confusion matrix saved.")

import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

# Compute metrics
accuracy = accuracy_score(y_test_m, pred)
f1_macro = f1_score(y_test_m, pred, average='macro')
f1_weighted = f1_score(y_test_m, pred, average='weighted')

performance_df = pd.DataFrame({
    "Metric": ["Accuracy", "Macro F1", "Weighted F1"],
    "Value": [accuracy, f1_macro, f1_weighted]
})

# Save as image
fig, ax = plt.subplots(figsize=(5,2))
ax.axis('off')
table = ax.table(cellText=performance_df.values,
                 colLabels=performance_df.columns,
                 loc='center')

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1, 1.5)

plt.savefig("results/performance_table.png", dpi=300, bbox_inches='tight')
plt.close()

print("Performance table saved.")

from google.colab import files

files.download("results/confusion_matrix.png")
files.download("results/performance_table.png")

"""## 19. Key findings

Suggested points to cover:
1. Which model performed best in the early stage and why that matters for early intervention.
2. How much the mid-term stage improved and what that suggests about the value of academic history.
3. What SHAP revealed about the strongest drivers of predictions.
4. What the calibration curve suggests about probability reliability.

"""